name: format-taginfo-docs

on:
  workflow_call:

jobs:
  format-taginfo-docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Python
        uses: ./.github/actions/install-python

      - name: Prepare environment
        run: |
          npm ci --ignore-scripts
          clang-format-15 --version

      - name: Run checks
        run: |
          ./scripts/check_taginfo.py taginfo.json profiles/car.lua
          ./scripts/format.sh && ./scripts/error_on_dirty.sh
          node ./scripts/validate_changelog.js
          npm audit --omit=dev

      - name: Build docs
        run: |
          # npm run docs
          make -C docs

      - name: Upload Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/docs/
